name: CI/CD counter app

on:
  push:
    branches: [ main ]
    
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: self-hosted

    steps:
      - name: checkout the files
        uses: actions/checkout@v2

      - name: deploy to the server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_KKEY_PAIR }}
          REMOTE_HOST: ${{ secrets.EC2_IP }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
