name: CI/CD counter app

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the docker_compose
      run: docker-compose up -d --build

    - name: Start the application (dev mode)
      run: docker-compose exec -T fraud-service npm run dev

  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_KKEY_PAIR  }}
            HOSTNAME : ${{ secrets.EC2_IP }}
            USER_NAME : ${{ secrets.USERNAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/YourReactApp
            git checkout master
            git fetch --all
            git reset --hard origin/master
            git pull origin master
            docker-compose -f docker-compose.prod.yml up -d --build'
