name: CI/CD counter app

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: self-hosted # It can be self-hosted or ubuntu-latest depending on your setup

    steps:
      - name: checkout the files
        uses: actions/checkout@v2

      - name: Install dependencies and run server
        run: |
          cd /home/ubuntu/actions-runner/_work/fdd/fdd
         
