name: CI/CD counter app

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    

  Deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_KKEY_PAIR }}
            HOSTNAME : ${{ secrets.EC2_IP }}
            USER_NAME : ${{ secrets.USERNAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./ ${USER_NAME}@${HOSTNAME}:/home/ubuntu/your-app-directory
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu/your-app-directory
            npm install
            npm run dev'
