name: CI/CD counter app

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    

  Deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_KKEY_PAIR }}
            HOSTNAME : ${{ secrets.EC2_IP }}
            USER_NAME : ${{ secrets.USERNAME  }}

        run: 
          
            cd /home/ubuntu/actions-runner/_work/fdd/fdd
            npm install
            npm run dev'
